*** Settings ***
Resource                            ${CURDIR}/../../robot/dpi-keywords.robot
Resource                            ${CURDIR}/../../robot/access-peripheral-keywords.robot
Test Teardown                       Run Keywords
...                                 Test Teardown
...                                 Terminate And Log

*** Variables ***
${DPI_PLATFORM}                     ${CURDIR}/platform.resc
${BUILD_DIRECTORY}                  ${CURDIR}/build
${VERILATED_BINARY}                 ${BUILD_DIRECTORY}/verilated
${QUESTA_WORK_LIBRARY}              ${BUILD_DIRECTORY}/work_questa

${DUT}                              requester


*** Keywords ***
Create Machine
    Execute Command                 include @${DPI_PLATFORM}

Memory Should Contain
    [Arguments]                     ${addr}  ${val}
    ${res}=                         Execute Command  mem ReadDoubleWord ${addr}
    Should Contain                  ${res}  ${val}

Post Emulation Memory Should Contain
    # The values below are generated by the System Verilog module.
    # This module is an APB Requester.
    # Renode receives data as an APB Completer.
    Memory Should Contain           0x00000000  0x000AA000
    Memory Should Contain           0x00000004  0x000AA004
    Memory Should Contain           0x00000008  0x000AA008
    Memory Should Contain           0x0000000C  0x000AA00C
    Memory Should Contain           0x00000010  0x000AA010
    Memory Should Contain           0x00000014  0x000AA014
    Memory Should Contain           0x00000018  0x000AA018
    Memory Should Contain           0x0000001C  0x000AA01C

    Memory Should Contain           0x00001000  0x000BB000
    Memory Should Contain           0x00001100  0x000BB100
    Memory Should Contain           0x00001200  0x000BB200
    Memory Should Contain           0x00001004  0x000BB004
    Memory Should Contain           0x00001104  0x000BB104
    Memory Should Contain           0x00001204  0x000BB204
    Memory Should Contain           0x00001008  0x000BB008
    Memory Should Contain           0x00001108  0x000BB108
    Memory Should Contain           0x00001208  0x000BB208
    Memory Should Contain           0x0000100C  0x000BB00C
    Memory Should Contain           0x0000110C  0x000BB10C
    Memory Should Contain           0x0000120C  0x000BB20C
    Memory Should Contain           0x00001010  0x000BB010
    Memory Should Contain           0x00001110  0x000BB110
    Memory Should Contain           0x00001210  0x000BB210
    Memory Should Contain           0x00001014  0x000BB014
    Memory Should Contain           0x00001114  0x000BB114
    Memory Should Contain           0x00001214  0x000BB214
    Memory Should Contain           0x00001018  0x000BB018
    Memory Should Contain           0x00001118  0x000BB118
    Memory Should Contain           0x00001218  0x000BB218
    Memory Should Contain           0x0000101C  0x000BB01C
    Memory Should Contain           0x0000111C  0x000BB11C
    Memory Should Contain           0x0000121C  0x000BB21C


*** Test Cases ***
Should Connect Verilator
    [Tags]                          verilator
    Should Connect To Verilator And Reset Peripheral  ${DUT}  ${VERILATED_BINARY}  Create Machine

Should Connect Questa
    [Tags]                          questa
    Should Connect To Questa And Reset Peripheral  ${DUT}  ${QUESTA_WORK_LIBRARY}  Create Machine

Should Read And Write Memory In Verilator
    [Tags]                          verilator
    Create Machine
    Connect To Verilator            ${DUT}  ${VERILATED_BINARY}

    Execute Command                 emulation RunFor "00:00:0.001"
    Post Emulation Memory Should Contain

Should Read And Write Memory In Questa
    [Tags]                          questa
    Create Machine
    Connect To Questa               ${DUT}  ${QUESTA_WORK_LIBRARY}

    Execute Command                 emulation RunFor "00:00:0.001"
    Post Emulation Memory Should Contain
