name: Build Renode
description: Builds Renode from source from the specified repository and revision
inputs:
  renode_git_repo:
    description: Renode git repository
    required: true
    default: https://github.com/renode/renode
  renode_git_ref:
    description: Renode git revision
    required: true
    default: master
runs:
  using: composite
  steps:
    - id: get-renode-rev
      run: |
        git clone "${{ inputs.renode_git_repo }}" renode
        git -C renode checkout "${{ inputs.renode_git_ref }}" --
        rev="$(git -C renode rev-parse @)"
        echo "renode-rev="$rev"" >> "$GITHUB_OUTPUT"
        mv renode "renode-$rev-cloned"
      shell: bash
      working-directory: ${{ runner.temp }}
    - uses: actions/cache/restore@v4
      id: restore-cache
      with:
        path: ${{ runner.temp }}/renode-${{ steps.get-renode-rev.outputs.renode-rev }}
        key: renode-${{ runner.os }}-${{ runner.arch }}-${{ steps.get-renode-rev.outputs.renode-rev }}
    # Remove the just-cloned source if a cached build was found
    - run: |
        rm -rf renode-${{ steps.get-renode-rev.outputs.renode-rev }}-cloned
      shell: bash
      working-directory: ${{ runner.temp }}
      if: ${{ steps.restore-cache.outputs.cache-hit == 'true' }}
    - run: |
        mv renode-${{ steps.get-renode-rev.outputs.renode-rev }}-cloned renode-${{ steps.get-renode-rev.outputs.renode-rev }}
        cd renode-${{ steps.get-renode-rev.outputs.renode-rev }}
        echo Building "${{ inputs.renode_git_repo }}" at "${{ inputs.renode_git_ref }} (${{ steps.get-renode-rev.outputs.renode-rev }})"
        git submodule update --init --recursive --depth=1
      shell: bash
      working-directory: ${{ runner.temp }}
      if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
    - name: Install dependencies (Linux)
      run: |
        sudo apt-get -qqy update
        sudo apt-get -y install --no-install-recommends cmake mono-complete policykit-1 libgtk2.0-dev uml-utilities gtk-sharp2
      shell: bash
      if: ${{ runner.os == 'Linux' }}
    - name: Build Renode (Mono)
      run: |
        ./build.sh
        # delete some unneeded dirs to slim down the cache entry
        find . -name .git -exec rm -rf '{}' '+'
        find lib src '-(' -name bin -or -name obj '-)' -exec rm -rf '{}' '+'
      shell: bash
      working-directory: ${{ runner.temp }}/renode-${{ steps.get-renode-rev.outputs.renode-rev }}
      if: ${{ runner.os != 'Windows' && steps.restore-cache.outputs.cache-hit != 'true' }}
    # For Windows, build and extract a package to generate the wrapper batch scripts
    - name: Build Renode (.NET Framework)
      run: |
        cd renode-${{ steps.get-renode-rev.outputs.renode-rev }}
        curl https://repo.msys2.org/msys/x86_64/zip-3.0-3-x86_64.pkg.tar.xz | tar xOJ usr/bin/zip.exe > zip.exe
        msbuild="$(vswhere -latest -requires Microsoft.Component.MSBuild -find 'MSBuild\**\Bin\MSBuild.exe' | tr '\\' '/')"
        export PATH="$PATH:$(cygpath "$(dirname "$msbuild")"):$PWD"
        export MSYS=winsymlinks:nativestrict
        ./build.sh -p
        mv output/packages/*.zip ../renode.zip
        cd ..
        rm -rf renode-*
        unzip renode.zip
        rm renode.zip
        mv renode* renode-${{ steps.get-renode-rev.outputs.renode-rev }}
      shell: bash
      working-directory: ${{ runner.temp }}
      if: ${{ runner.os == 'Windows' && steps.restore-cache.outputs.cache-hit != 'true' }}
    - uses: actions/cache/save@v4
      with:
        path: ${{ runner.temp }}/renode-${{ steps.get-renode-rev.outputs.renode-rev }}
        key: renode-${{ runner.os }}-${{ runner.arch }}-${{ steps.get-renode-rev.outputs.renode-rev }}
      if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
    - name: Install Robot framework dependencies
      run: python3 -m pip install -r tests/requirements.txt
      shell: bash
      working-directory: ${{ runner.temp }}/renode-${{ steps.get-renode-rev.outputs.renode-rev }}
    - name: Setup environment (Linux/macOS)
      run: |
        echo "${{ runner.temp }}/renode-${{ steps.get-renode-rev.outputs.renode-rev }}" >> "$GITHUB_PATH"
        echo "RENODE_ROOT=${{ runner.temp }}/renode-${{ steps.get-renode-rev.outputs.renode-rev }}" >> "$GITHUB_ENV"
      shell: bash
      if: ${{ runner.os != 'Windows' }}
    - name: Setup environment (Windows)
      run: |
        echo "${{ runner.temp }}/renode-${{ steps.get-renode-rev.outputs.renode-rev }}/bin" >> "$GITHUB_PATH"
        echo "RENODE_ROOT=${{ runner.temp }}/renode-${{ steps.get-renode-rev.outputs.renode-rev }}" >> "$GITHUB_ENV"
      shell: bash
      if: ${{ runner.os == 'Windows' }}
